#include <errno.h>

#include "../measure/profile.h"
#include "../common/nodekey_mapping.h"
#include "../common/ancillary.h"
#include "../common/config.h"
#include "../common/packet.h"

extern conf_t* conf;
extern struct PacketStat packet_stat;

int main (int argc, char *argv []) {

	if (argc != 2) {
		LOG_ERR("Usage: %s [config file]\n", argv[0]);
	}

	// get config information
	conf = Config_Init(argv[1]);
	const char* dir = conf_common_data_dir(conf);
	const char* save_dir = conf_common_save_dir(conf);
	if (access(save_dir, 0) == -1) {
		LOG_ERR("No such dir %s\n", save_dir);
	}

	// open packet stat file
	const char* packet_stat_file = conf_common_packet_stat_file(conf);
	const char* packet_stat_path = path_join(dir, packet_stat_file);
	FILE* stat_fd = fopen(packet_stat_path, "rb");
	if (stat_fd == NULL) {
		LOG_ERR("cannot open %s: %s\n", packet_stat_path, strerror(errno));
	}

	// read packet stat
	int stat_cnt = fread(&packet_stat, sizeof(PacketStat), 1, stat_fd);
	if (stat_cnt != 1) {
		LOG_ERR("Invalid read element count %d of packet stat which should be %d: %s\n",
				stat_cnt, 1, strerror(errno));
	}
	fclose(stat_fd);

	// create objects for profile
	c_nodekey_mapping_t<c_subset_key_t> subset_nodekey_mapping[3]; // subset level 1, 2, 3
	c_nodekey_mapping_t<c_host_key_t> host_nodekey_mapping;
	c_nodekey_mapping_t<c_app_key_t> app_nodekey_mapping;
	c_flow_record_t flow_record = c_flow_record_t(packet_stat.trace_start_ts, packet_stat.trace_end_ts);

	// open record file which is generated by trace_process module
	const char* record_file = conf_common_record_file(conf);
	const char* record_path = path_join(dir, record_file);
	FILE* record_fd = fopen(record_path, "rb");
	if (record_fd == NULL) {
		LOG_ERR("cannot open %s: %s\n", record_path, strerror(errno));
	}

	uint64_t start_ts = now_us();

	// read tuples and udpate statistics
	tuple_t t;
	uint32_t packet_cnt = 0;
	while (1) {
		int read_cnt = fread(&t, sizeof(tuple_t), 1, record_fd);
		if (read_cnt != 1) {
			if (ferror(record_fd)) {
				LOG_ERR("read record file error: %s\n",strerror(errno));
			}
			else if (feof(record_fd)) {
				LOG_MSG("read record file end\n");
				break;
			}
			else {
				LOG_ERR("read record file error: unknown error\n");
			}
		}

		// Test ip representation under little endian
		// char tmp_str[100];
		/*c_host_key_t tmp_h = c_host_key_t(t.key.src_ip);*/
		/*tmp_h.to_string(tmp_str);*/
		/*printf("%s\n",tmp_str);*/
		/*c_subset_key_t tmp_s = c_subset_key_t(t.key.src_ip);*/
		/*tmp_s.to_string(tmp_str);*/
		/*printf("%s\n",tmp_str);*/
		/*exit(0);*/

		// update index mapping of subset key
		for (uint32_t i = 0; i < 3; i++) {
			c_subset_key_t tmp_src_subset = c_subset_key_t(t.key.src_ip, i+1);
			c_subset_key_t tmp_dst_subset = c_subset_key_t(t.key.dst_ip, i+1);
			subset_nodekey_mapping[i].insert_key(tmp_src_subset);
			subset_nodekey_mapping[i].insert_key(tmp_dst_subset);
		}

		// update index mapping of host key
		c_host_key_t tmp_src_host = c_host_key_t(t.key.src_ip);
		c_host_key_t tmp_dst_host = c_host_key_t(t.key.dst_ip);
		host_nodekey_mapping.insert_key(tmp_src_host);
		host_nodekey_mapping.insert_key(tmp_dst_host);

		// update index mapping of app key
		c_app_key_t src_app = c_app_key_t(t.key.src_ip, t.key.src_port);
		c_app_key_t dst_app = c_app_key_t(t.key.dst_ip, t.key.dst_port);
		app_nodekey_mapping.insert_key(src_app);
		app_nodekey_mapping.insert_key(dst_app);

		// update flow record
		flow_record.update_record(t);

		packet_cnt++;
	}
	fclose(record_fd);

	uint64_t end_ts = now_us();
	LOG_MSG("time cost: %ld us\n", end_ts - start_ts);

	// Test active flow number for a specific time index
	/*uint32_t time_cnt = flow_record.get_time_interval_cnt();*/
	/*if (time_cnt > 100) {*/
		/*time_cnt = 100;*/
	/*}*/
	/*uint32_t cnt[time_cnt];*/
	/*memset(cnt, 0, sizeof(uint32_t)*time_cnt);*/
	/*for (uint32_t i = 0; i < time_cnt; i++) {*/
		/*cnt[i] = flow_record.get_number(i);*/
	/*}*/
	/*for (uint32_t i = 0; i < time_cnt; i++) {*/
		/*if (cnt[i] > 0) {*/
			/*printf("[%d] %d\n", i, cnt[i]);*/
		/*}*/
	/*}*/

	// save profile
	
	LOG_MSG("packet number: %d\n", packet_cnt);
	
	// save subset index mapping
	const char* subset_mapping_file = conf_common_subset_mapping_file(conf);
	const char* subset_mapping_path = path_join(save_dir, subset_mapping_file);
	for (uint32_t i = 0; i < 3; i++) {
		char tmp_subset_path[100];
		sprintf(tmp_subset_path, "%s.%d", subset_mapping_path, i+1);
		subset_nodekey_mapping[i].save(tmp_subset_path);
		LOG_MSG("subset %d number: %d\n", i+1, subset_nodekey_mapping[i].get_number());
	}

	// save host index mapping
	const char* host_mapping_file = conf_common_host_mapping_file(conf);
	const char* host_mapping_path = path_join(save_dir, host_mapping_file);
	host_nodekey_mapping.save(host_mapping_path);
	LOG_MSG("host number: %d\n", host_nodekey_mapping.get_number());

	// save app index mapping
	const char* app_mapping_file = conf_common_app_mapping_file(conf);
	const char* app_mapping_path = path_join(save_dir, app_mapping_file);
	app_nodekey_mapping.save(app_mapping_path);
	LOG_MSG("app number: %d\n", app_nodekey_mapping.get_number());

	// save flow records
	const char* flow_record_file = conf_common_flow_record_file(conf);
	const char* flow_record_path = path_join(save_dir, flow_record_file);
	flow_record.save(flow_record_path);
	LOG_MSG("flow nubmer: %d\n", flow_record.get_number());
}
